send-alarm-parameters: &send-alarm-parameters
  alarm_priority: "P3"
  alarm_description: "The pipeline has failed"
  genie_key: ((genie_key))
resources:
- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/giva01121/concourse-resourcetype-helloworld.git
    branch: master
jobs:
- name: example_alarm
  plan:
  - get: concourse-pipelines
  - task: deploy
    file: concourse-pipelines/tasks/task.yml
    params:
      <<: *send-alarm-parameters
      alarm_message: "[TESTING]IGNORE_THIS_ALERT"
      alarm_alias: "Something"
