resource_types:
- name: custom-resource
  type: docker-image
  source:
    # set repo of your custom-resource resource
    #repository: Your-Docker-Acct/Your-Docker-Repository
    ## or use my custom-resource resource
    repository: swce/metadata-resource

resources:
- name: concourse-pipelines
  type: git
  source:
    uri: https://github.com/giva01121/concourse-resourcetype-helloworld.git
    branch: master
- name: custom-resource
  type: custom-resource

jobs:
- name: hello-job
  plan:
  - get: concourse-pipelines
  - get: custom-resource
  - task: prod-deploy
    file: concourse-pipelines/tasks/task.yml