platform: linux
image_resource:
  type: registry-image
  source:
    repository: schwarzit-xx-sit-appcloud-docker-local.jfrog.io/a9s-automation
    username: ((jfrog_user))
    password: ((jfrog_password))
    tag: latest
container_limits:
  cpu: 2
  memory: 4gb
inputs:
  - name: concourse-pipelines
  - name: custom-resource
run:
  path: sh
  args:
    - -ec
    - |
      BUILD_NUMBER=`cat custom-resource/build-name`
      echo "BUILD_NUMBER is $BUILD_NUMBER"

      JOB_NAME=`cat custom-resource/build-job-name`
      echo "JOB_NAME is $JOB_NAME"

      PIPELINE_NAME=`cat custom-resource/build-pipeline-name`
      echo "PIPELINE_NAME is $BUILD_PIPELINE_NAME"

      TEAM_NAME=`cat custom-resource/build-team-name`
      echo "TEAM_NAME is $BUILD_TEAM_NAME"
      
      ATC_EXTERNAL_URL=`cat custom-resource/atc-external-url`
      echo "CONCOURSE_URL is $ATC_EXTERNAL_URL"
