platform: linux
image_resource:
  type: registry-image
  source:
    repository: schwarzit-xx-sit-appcloud-docker-local.jfrog.io/metadata-resource
    username: ((jfrog_user))
    password: ((jfrog_password))
    tag: latest
container_limits:
  cpu: 2
  memory: 4gb
inputs:
  - name: concourse-pipelines
  - name: custom-resource
run:
  path: sh
  args:
    - -ec
    - |
      concourse-pipelines/tasks/alarm.sh "${alarm_priority}" "${alarm_message}" "${alarm_description}" "${alarm_alias}"
